---
- name: Установка MariaDB на Debian
  hosts: srv-db
  become: yes
  vars_files:
    vars.yml

  tasks:
    - name: Установка MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Запуск MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Установка python3-pymysql для работы с MySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Удаление анонимных пользователей
      community.mysql.mysql_user:
        name: ''
        host_all: true
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock # при первом запуске
        #login_password: "{{ mariadb_root_password }}" # при последующих запусках

    - name: Запрет удалённого входа для root
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock # при первом запуске
        #login_password: "{{ mariadb_root_password }}" # при последующих запусках
      loop:
        - "{{ ansible_hostname }}"
        - '%'
        - '::1'
        - '127.0.0.1'

    - name: Удаление тестовой базы данных
      community.mysql.mysql_db:
        name: test
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
        #login_password: "{{ mariadb_root_password }}"

    - name: Установка пароля root@localhost
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        #login_password: "{{ mariadb_root_password }}"
        state: present

    - name: Убеждаемся, что строка bind-address существует и установлена в 0.0.0.0
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        insertafter: '^\[mysqld\]'
        backup: yes

    - name: Перезапускаем MariaDB
      systemd:
        name: mariadb
        state: restarted

    - name: Получить IP-адрес srv-web
      set_fact:
        web_ip: "{{ hostvars['srv-web']['ansible_host'] }}"

    - name: Создание пользователя для phpmyadmin
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        host: "{{ web_ip }}"
        password: "{{ phpmyadmin_password }}"
        priv: "*.*:ALL PRIVILEGES,GRANT"
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        login_host: localhost
        state: present