---
- name: Установка MariaDB на Debian
  hosts: srv-db
  become: yes
  vars:
    mariadb_root_password: "MyStrongPassword"
    db_name: "mydb"
    db_user: "myuser"
    db_password: "12345"

  tasks:
    - name: Установка MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Запуск MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Установка python3-pymysql для работы с MySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Удаление анонимных пользователей
      community.mysql.mysql_user:
        name: ''
        host_all: true
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock # при первом запуске
        #login_password: "{{ mariadb_root_password }}" # при последующих запусках

    - name: Запрет удалённого входа для root
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock # при первом запуске
        #login_password: "{{ mariadb_root_password }}" # при последующих запусках
      loop:
        - "{{ ansible_hostname }}"
        - '%'
        - '::1'
        - '127.0.0.1'

    - name: Удаление тестовой базы данных
      community.mysql.mysql_db:
        name: test
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
        #login_password: "{{ mariadb_root_password }}"

    - name: Установка пароля root@localhost
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        #login_password: "{{ mariadb_root_password }}"
        state: present

    - name: Убеждаемся, что строка bind-address существует и установлена в 0.0.0.0
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        insertafter: '^\[mysqld\]'
        backup: yes

    - name: Перезапускаем MariaDB
      systemd:
        name: mariadb
        state: restarted

    - name: Создание базы данных
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Создание пользователя для базы данных
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        host: "%"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
