---
- name: Установка phpMyAdmin
  hosts: srv-web
  become: true
  vars:
    pma_url: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
    pma_dest_dir: /var/www/html/phpMyAdmin
    pma_tmp_file: /tmp/phpMyAdmin.tar.gz

  tasks:
    - name: Установка php8.2-mysql
      apt:
        name: php8.2-mysql
        state: present
        update_cache: yes

    - name: Установка php8.2-mbstring
      apt:
        name: php8.2-mbstring
        state: present
        update_cache: yes

    - name: Скачиваем phpMyAdmin архив
      get_url:
        url: "{{ pma_url }}"
        dest: "{{ pma_tmp_file }}"

    - name: Создаём каталог для phpMyAdmin
      file:
        path: "{{ pma_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Распаковываем phpMyAdmin в целевой каталог
      unarchive:
        src: "{{ pma_tmp_file }}"
        dest: "{{ pma_dest_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Копируем config.sample.inc.php в config.inc.php
      copy:
        src: "{{ pma_dest_dir }}/config.sample.inc.php"
        dest: "{{ pma_dest_dir }}/config.inc.php"
        remote_src: yes
        force: no  # не перезаписывает, если уже есть

    - name: Настройка phpMyAdmin config.inc.php
      copy:
        dest: "{{ pma_dest_dir }}/config.inc.php"
        content: |
          <?php
          declare(strict_types=1);
          $cfg['blowfish_secret'] = 'a8fjGhd837djf9Kdk73hf92kdmf93KD8';
          $i = 0;
          $i++;
          $cfg['Servers'][$i]['host'] = '192.168.10.35';
          $cfg['Servers'][$i]['port'] = '3306';
          $cfg['Servers'][$i]['user'] = 'myuser';
          $cfg['Servers'][$i]['password'] = '12345';
          $cfg['Servers'][$i]['auth_type'] = 'cookie';
          $cfg['Servers'][$i]['compress'] = false;
          $cfg['Servers'][$i]['AllowNoPassword'] = false;
        owner: www-data
        group: www-data
        mode: '0660'

    - name: Перезапускаем nginx
      systemd:
        name: nginx
        state: restarted
