---
- name: Установка NGINX и PHP на сервер
  hosts: srv-web
  become: true
  tasks:
    - name: Установка NGINX и PHP
      apt:
        name:
          - nginx
          - php-fpm
        state: present
        update_cache: true

    - name: Убедиться, что NGINX запущен
      service:
        name: nginx
        state: started
        enabled: true

    - name: Создание NGINX-конфига для PHP
      copy:
        dest: /etc/nginx/sites-available/php_site
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.php index.html;

              location / {
                  try_files $uri $uri/ =404;
              }

              location /phpMyAdmin {
                  try_files $uri $uri/ =404;
              }

              location ~ ^/phpMyAdmin/(.*\.php)$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              }

              location ~ ^/phpMyAdmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
                expires max;
                log_not_found off;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              }
          }

    - name: Включение сайта (симлинк)
      file:
        src: /etc/nginx/sites-available/php_site
        dest: /etc/nginx/sites-enabled/php_site
        state: link
        force: true

    - name: Удалить default-сайт (если есть)
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Создать index.php в веб-каталоге
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
          phpinfo();
          ?>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Проверить конфиг NGINX
      command: nginx -t
      register: nginx_test
      failed_when: "'successful' not in nginx_test.stderr"

    - name: Перезапустить NGINX
      service:
        name: nginx
        state: restarted
