---
- name: Установка MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Запуск MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Установка python3-pymysql для работы с MySQL
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Удаление анонимных пользователей
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Запрет удалённого входа для root
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - "{{ ansible_hostname }}"
    - '%'
    - '::1'
    - '127.0.0.1'

- name: Удаление тестовой базы данных
  community.mysql.mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Получить IP-адрес srv-web
  set_fact:
    web_ip: "{{ hostvars['srv-web']['ansible_host'] }}"

- name: Создание пользователя для phpmyadmin
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    host: "{{ web_ip }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL PRIVILEGES,GRANT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Убеждаемся, что bind-address установлена в 0.0.0.0
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    insertafter: '^\[mysqld\]'
    backup: yes

- name: Перезапускаем MariaDB
  systemd:
    name: mariadb
    state: restarted